### ISSUE TITLE
Android crash

### ISSUE THREAD

**Issue by iclems** [datso/react-native-pjsip#11]
03-06 19:01:44.191 E/PjSipService( 3370): Error while loading OpenH264 native library
03-06 19:01:44.191 E/PjSipService( 3370): java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/.../lib/x86/libopenh264.so: has text relocations
03-06 19:01:44.191 E/PjSipService( 3370): 	at java.lang.Runtime.loadLibrary(Runtime.java:372)
03-06 19:01:44.191 E/PjSipService( 3370): 	at java.lang.System.loadLibrary(System.java:1076)
03-06 19:01:44.191 E/PjSipService( 3370): 	at com.carusto.ReactNativePjSip.PjSipService.load(PjSipService.java:157)
03-06 19:01:44.191 E/PjSipService( 3370): 	at com.carusto.ReactNativePjSip.PjSipService.access$000(PjSipService.java:36)
03-06 19:01:44.191 E/PjSipService( 3370): 	at com.carusto.ReactNativePjSip.PjSipService$1.run(PjSipService.java:149)
03-06 19:01:44.191 E/PjSipService( 3370): 	at android.os.Handler.handleCallback(Handler.java:739)
03-06 19:01:44.191 E/PjSipService( 3370): 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-06 19:01:44.191 E/PjSipService( 3370): 	at android.os.Looper.loop(Looper.java:148)
03-06 19:01:44.191 E/PjSipService( 3370): 	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by iclems** [comment]
This is an issue that occurred with other projects as well. e.g. https://github.com/wseemann/FFmpegMediaPlayer/issues/64

The temporary solution is that the target SDK cannot be > 22.

**Comment by datso** [comment]
How can I reproduce it ?

**Comment by iclems** [comment]
Set target SDK to anything > 22 and try to run the app. It will crash at launch.

**Comment by rcorrie** [comment]
I am seeing this error as well. On SDK 23

**Comment by nikhildaga** [comment]
We are facing it as well. This is the error 

![screenshot_1515450118](https://user-images.githubusercontent.com/655017/34695713-af5974d8-f480-11e7-8f7c-59cb80b03756.png)

**Comment by datso** [comment]
Fixed in 2.7.1

**Comment by mehdinourollah** [comment]
No it's not fixed ! I'm using version 2.8  but getting this error still...
![image](https://user-images.githubusercontent.com/5097056/104558986-c3f83f80-5654-11eb-832b-d16c0c3a42f9.png)
